import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { AxiosResponse } from "axios";
import { fetchCategories } from "../http";
import { ICategory, ICollectionResponse } from "../types";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Blog Post</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-red-900 font-bold underline">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async () => {
  //categories
  const { data: categories }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  console.log({ cat: categories.data });

  return {
    props: {
      categories: {
        items: categories?.data,
      },
    },
  };
};

export default Home;
